# Generated by Django 3.1.2 on 2020-11-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_keds_sneekers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keds',
            name='keds_name',
        ),
        migrations.RemoveField(
            model_name='sneekers',
            name='sneekers_name',
        ),
    ]
