# Generated by Django 3.1.2 on 2020-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201203_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
